# З Informaci贸n general del sitio 
title: "Carlos Esteban Ortiz Espitia"
#logo: "/assets/profile.jpg"
description: |
  <div style="text-align: justify;">
  <strong>Data Analyst | Mechanical Engineer | Cybersecurity | MBA</strong><br><br>
  Soy Ingeniero Mec谩nico y Analista de Datos Junior Biling眉e, con m谩s de 5 a帽os de experiencia en sectores industriales, empresariales y de gesti贸n.
  A lo largo de mi trayectoria he liderado proyectos t茅cnicos y estrat茅gicos enfocados en la mejora de procesos, eficiencia operativa y reducci贸n de costos, aportando soluciones con impacto real.<br><br>
  Me defino por una visi贸n estrat茅gica, capacidad de liderar equipos diversos e impulsar la innovaci贸n combinando tecnolog铆a, an谩lisis de datos y liderazgo.
  Especializado en Ciberseguridad y An谩lisis de Datos, domino herramientas como Python, SQL, Pandas, Numpy, Tableau, Power BI, Streamlit, Jupyter Notebook, Git/GitHub y Excel avanzado.
  He aplicado t茅cnicas de machine learning (regresi贸n, clasificaci贸n y clustering), an谩lisis estad铆stico y visualizaci贸n de datos para generar insights accionables que impulsan la toma de decisiones.<br><br>
   <a href="https://github.com/Carloseortize" target="_blank">GitHub</a> |
  <a href="https://www.linkedin.com/in/carlos-esteban-ortiz-espitia/" target="_blank">LinkedIn</a> |
  <a href="mailto:carloseortize@gmail.com">Correo</a>
  </div>

theme: jekyll-theme-minimal

#  Colecci贸n de proyectos
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# 锔 Plugins compatibles con GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Ь Markdown y resaltado de c贸digo
markdown: kramdown
highlighter: rouge

#  Archivos que no se deben incluir
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - _site
  - LICENSE
